'use client';
import { useEffect, useMemo, useState } from 'react';
const empty=()=>({id:'',name:'',placeIds:'',aliases:'',url:''});
function toForm(g){return {...g,placeIds:(g.placeIds||[]).join(', '),aliases:(g.aliases||[]).join(', ')};}
function toData(g){return {...g,placeIds:String(g.placeIds||'').split(/[\s,;]+/).filter(Boolean),aliases:String(g.aliases||'').split(',').map(x=>x.trim()).filter(Boolean)};}
export default function GameManager(){
 const [games,setGames]=useState([]),[edit,setEdit]=useState(null),[form,setForm]=useState(empty()),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[custom,setCustom]=useState(false);
 async function load(){setBusy(true);try{const r=await fetch('/api/admin/games',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'โหลดข้อมูลไม่สำเร็จ');setGames((d.games||[]).map(toForm));setCustom(!!d.custom);setMessage('');}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>games.filter(g=>(g.name+' '+g.id+' '+g.placeIds+' '+g.aliases).toLowerCase().includes(query.toLowerCase())),[games,query]);
 function startNew(){setEdit(-1);setForm(empty());}
 function startEdit(i){setEdit(i);setForm({...games[i]});}
 function update(k,v){setForm(p=>({...p,[k]:v}));}
 function saveLocal(){if(!form.name.trim()){setMessage('กรุณากรอกชื่อแมพ');return}if(form.url.trim()&&!/^https:\/\//i.test(form.url.trim())){setMessage('URL ต้องขึ้นต้นด้วย https://');return}const next={...form,id:form.id.trim()||form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),placeIds:form.placeIds,aliases:form.aliases};if(edit===-1)setGames(p=>[...p,next]);else setGames(p=>p.map((g,i)=>i===edit?next:g));setEdit(null);setMessage('แก้ไขรายการในแบบร่างแล้ว กด “บันทึกทั้งหมด” เพื่อใช้งานจริง');}
 function remove(i){if(!confirm(`ลบแมพ “${games[i].name}” ออกจากรายการหรือไม่?`))return;setGames(p=>p.filter((_,n)=>n!==i));setMessage('ลบออกจากแบบร่างแล้ว กด “บันทึกทั้งหมด” เพื่อยืนยัน');}
 async function publish(){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/games',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({games:games.map(toData)})});const d=await r.json();if(!r.ok)throw Error(d.error||'บันทึกไม่สำเร็จ');setGames((d.games||[]).map(toForm));setCustom(true);setMessage('บันทึกสำเร็จ — การตั้งค่าแมพถูกนำไปใช้กับ Loader แล้ว');}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function reset(){if(!confirm('คืนค่ารายการแมพเริ่มต้นของโปรเจกต์หรือไม่?'))return;setBusy(true);try{const r=await fetch('/api/admin/games',{method:'DELETE'});const d=await r.json();if(!r.ok)throw Error(d.error||'คืนค่าไม่สำเร็จ');await load();setMessage('คืนค่ารายการเริ่มต้นแล้ว');}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="gm-wrap">
  <div className="gm-head"><div><h2 className="h2" style={{margin:'0 0 5px'}}>จัดการแมพของ Loader</h2><div className="gm-muted">เพิ่มแมพ · เปลี่ยน Place ID · เปลี่ยน URL · จับคู่ด้วยชื่อ</div></div><span className="gm-count">{games.length} MAPS</span></div>
  <div className="gm-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาชื่อ / ID / Place ID..."/><button className="btn ghost" onClick={startNew}>＋ เพิ่มแมพ</button><button className="btn" disabled={busy} onClick={publish}>{busy?'กำลังบันทึก…':'บันทึกทั้งหมด'}</button></div>
  {message&&<div className="gm-message" role="status">{message}</div>}
  {edit!==null&&<div className="gm-editor"><div className="gm-editor-head"><b>{edit===-1?'เพิ่มแมพใหม่':'แก้ไขข้อมูลแมพ'}</b><button className="btn ghost" onClick={()=>setEdit(null)}>ปิด</button></div>
    <div className="gm-fields"><label>ชื่อแมพ<input value={form.name} onChange={e=>update('name',e.target.value)} placeholder="เช่น Murder Mystery 2"/></label><label>Map Key / ID<input value={form.id} onChange={e=>update('id',e.target.value)} placeholder="เช่น mm2"/><small>ใช้เป็นรหัสภายใน ควรเป็น a-z, 0-9 และ -</small></label><label>Place ID(s)<input value={form.placeIds} onChange={e=>update('placeIds',e.target.value)} placeholder="142823291, 123456789"/><small>ใส่ได้หลาย ID คั่นด้วยจุลภาค</small></label><label>ชื่ออื่นสำหรับจับคู่<input value={form.aliases} onChange={e=>update('aliases',e.target.value)} placeholder="MM2, Murder Mystery 2"/><small>ระบบใช้เมื่อ Place ID ไม่ตรง</small></label><label className="gm-full">Script URL<input value={form.url} onChange={e=>update('url',e.target.value)} placeholder="https://raw.githubusercontent.com/..."/><small>ต้องเป็นลิงก์ HTTPS ที่ส่งซอร์สสคริปต์โดยตรง</small></label></div>
    <div className="gm-editor-actions"><button className="btn" onClick={saveLocal}>ใช้ข้อมูลนี้ในแบบร่าง</button></div>
  </div>}
  <div className="gm-layout"><div className="gm-list">{filtered.map(g=>{const i=games.indexOf(g);return <article className="gm-item" key={`${g.id}-${i}`}><div className="gm-game-icon">{(g.name||'?').slice(0,1).toUpperCase()}</div><div className="gm-info"><b>{g.name}</b><small>KEY: {g.id||'ยังไม่ได้ตั้ง'} · PLACE: {g.placeIds||'จับคู่ด้วยชื่อ/ค่าเริ่มต้น'}</small><small className={g.url?'gm-url':'gm-empty'}>{g.url?'URL ตั้งค่าแล้ว':'ยังไม่มี URL — เลือกไม่ได้'}</small></div><div className="gm-actions"><button className="btn ghost" onClick={()=>startEdit(i)}>แก้ไข</button><button className="btn ghost" onClick={()=>remove(i)}>ลบ</button></div></article>})}{!filtered.length&&<div className="gm-empty-state">ไม่พบแมพที่ค้นหา</div>}</div>
   <aside className="gm-preview"><div className="gm-preview-top"><span className="gm-live-dot"/> ROBLOX · LOADER PREVIEW</div><div className="gm-mock"><div className="gm-mock-side"><div className="gm-mock-logo">F!</div><b>Flexozy</b><small>SCRIPT HUB</small><div className="gm-mock-tab active">◈ Recommend</div><div className="gm-mock-tab">▦ All Scripts</div><div className="gm-mock-tab">⚙ Settings</div></div><div className="gm-mock-main"><div className="gm-mock-title">All Scripts</div><div className="gm-mock-sub">Choose a game to run</div><div className="gm-mock-cards">{(filtered.length?filtered:games).slice(0,4).map((g,i)=><div className="gm-mock-card" key={g.id+'preview'}><div className="gm-mock-thumb">{(g.name||'?').slice(0,1).toUpperCase()}</div><div><b>{g.name}</b><small>{g.url?'พร้อมรัน':'ยังไม่มีลิงก์'}</small></div><span>›</span></div>)}</div><div className="gm-mock-note">ตัวอย่างจำลอง • หน้าตาจริงใน Roblox ยังคงใช้โค้ด Loader เดิม</div></div></div><div className="gm-preview-footer">{custom?'กำลังใช้รายการแมพที่บันทึกไว้':'ตัวอย่างรายการเริ่มต้น'} · {games.length} รายการ</div></aside>
  </div><div className="gm-bottom"><span>การแก้ไขจะมีผลหลังบันทึก และ endpoint <code>/loader</code> ยังคงส่ง Lua text/plain</span><button className="btn ghost" disabled={busy} onClick={reset}>คืนค่าเริ่มต้น</button></div>
 </section>;
}
