/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as RobloxRouteImport } from './routes/roblox'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TeamRouteImport } from './routes/team'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as WalletRouteImport } from './routes/wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const RobloxRoute = RobloxRouteImport.update({
  id: '/roblox',
  path: '/roblox',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/partners': typeof PartnersRoute
  '/roblox': typeof RobloxRoute
  '/scripts': typeof ScriptsRoute
  '/store': typeof StoreRoute
  '/team': typeof TeamRoute
  '/vault': typeof VaultRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/partners': typeof PartnersRoute
  '/roblox': typeof RobloxRoute
  '/scripts': typeof ScriptsRoute
  '/store': typeof StoreRoute
  '/team': typeof TeamRoute
  '/vault': typeof VaultRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/partners': typeof PartnersRoute
  '/roblox': typeof RobloxRoute
  '/scripts': typeof ScriptsRoute
  '/store': typeof StoreRoute
  '/team': typeof TeamRoute
  '/vault': typeof VaultRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/partners'
    | '/roblox'
    | '/scripts'
    | '/store'
    | '/team'
    | '/vault'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/partners'
    | '/roblox'
    | '/scripts'
    | '/store'
    | '/team'
    | '/vault'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/partners'
    | '/roblox'
    | '/scripts'
    | '/store'
    | '/team'
    | '/vault'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  PartnersRoute: typeof PartnersRoute
  RobloxRoute: typeof RobloxRoute
  ScriptsRoute: typeof ScriptsRoute
  StoreRoute: typeof StoreRoute
  TeamRoute: typeof TeamRoute
  VaultRoute: typeof VaultRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roblox': {
      id: '/roblox'
      path: '/roblox'
      fullPath: '/roblox'
      preLoaderRoute: typeof RobloxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  PartnersRoute: PartnersRoute,
  RobloxRoute: RobloxRoute,
  ScriptsRoute: ScriptsRoute,
  StoreRoute: StoreRoute,
  TeamRoute: TeamRoute,
  VaultRoute: VaultRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
